### ISSUE TITLE
Encoderrawcontrol Problem

### ISSUE THREAD

**Issue by msutas** [lamjonah/ThisArm_Firmware#1]
Hi,

Thanks for the excellent work. I am trying to use this firmware however I could not make it run properly.

After firmware installation I try to run rawencoderstage for setting up the arm, but when the encoder is turned the raw value is set back to 1500 immediately.

I have walked through the code and couldn't find the cause. In the below serial output the encoder turned rapidly in one direction for several steps. As seen on the output, the rawvalue is incremented and set back to 1500. 

RawEncoderStage: Servo: 1  RawValue: 1500 MappedAngle: 145.92
RawEncoderStage: Servo: 1  RawValue: 1500 MappedAngle: 145.92
RawEncoderStage: Servo: 1  RawValue: 1500 MappedAngle: 145.92
RawEncoderStage: Servo: 1  RawValue: 1500 MappedAngle: 145.92
RawEncoderStage: Servo: 1  RawValue: 1500 MappedAngle: 145.92
RawEncoderStage: Servo: 1  RawValue: 1501 MappedAngle: 146.01
RawEncoderStage: Servo: 1  RawValue: 1501 MappedAngle: 146.01
RawEncoderStage: Servo: 1  RawValue: 1501 MappedAngle: 146.01
RawEncoderStage: Servo: 1  RawValue: 1500 MappedAngle: 145.92
RawEncoderStage: Servo: 1  RawValue: 1500 MappedAngle: 145.92
RawEncoderStage: Servo: 1  RawValue: 1500 MappedAngle: 145.92
RawEncoderStage: Servo: 1  RawValue: 1500 MappedAngle: 145.92

Any help will be highly appreciated.

Thanks

Mehmet

**Comment by msutas** [comment]
Solved.

The problem was related to the encoder library. Pin 12 and 13 were not suitable for reading encoder. Pin 2 and 3 is a better choice on Arduino Nano when these pins are used encoder library is utilizing interrupts which is better for reading encoders.

Changing encoder pins to 2 and 3 solved the problem.

**Comment by JoLamMaker** [comment]
Hi Mehmet

Thanks for considering my code.

I remember I have a similar problem when I test on my encoders.
Usually it is caused by some wiring issue between encoder and the Arduino. (I swapped push button pin and channel pin at that time)

Please check whether:
1. The encoder you are using have proper push-up/push-down 
2. The pins connected correctly (some low-price model does not have proper labeling)
3. In case you are using boards other than Arduino UNO, please check out whether the pins 12/13 are available. (some model using 12/13 pins as customized purpose)

You may want to download the example code from the official site of library.
http://www.pjrc.com/teensy/td_libs_Encoder.html

Hope this help and please feel free to voice out when you need.

Thanks and regards
Jonah

**Comment by JoLamMaker** [comment]
Oh, I just realize you already solved the issue yourself.
I don't expect it will have problem on official boards like NANO
